fix(docs): add-a-component command argument typo fix
microsoft/fast-cli pull request #93
Opened 2022-07-20 20:12 UTC by walidBouguima

I updated the syntax of the sentence and fixed a typo assuming that what's meant is **pre-configured** not **pre-congured**.

# Pull Request

## 📖 Description

Docs update to fix typo in add-component page when explaining the arguments that should be supplied to the CLI command during component creation. 

### 🎫 Issues
Not applicable

## 👩‍💻 Reviewer Notes
Not applicable

## ✅ Checklist

### General

- [*] I have updated the project documentation to reflect my changes.

## ⏭ Next Steps
Not applicable

2022-07-20 20:38 UTC, janechu requested changes

2022-07-20 20:38 UTC, janechu commented on website/docs/add-a-component.md
> +A template `npm` package or local package can be specified. Or a selection of pre-configured named templates can be used.
```suggestion
A template `npm` package or local package can be specified, or a selection of pre-configured named templates can be used.
```

2022-07-20 20:38 UTC, janechu commented
Thanks @walidBouguima! Just a small change as that is intended to be a single sentence.

2022-07-21 15:34 UTC, walidBouguima commented
great @janechu! thanks for that.

2022-07-21 16:38 UTC, janechu approved these changes

2022-07-21 16:55 UTC, merged